url: http://engineering.clever-cloud.com
pygments: true
portal:
  website: &portal_website
    title: Website
    url:   http://www.clever-cloud.com
  list: [*portal_website]

paginate: 3

i:
  
  brand: Clever Cloud Engineering Blog
  title:
    en: Engineer
  home: Home
  
  nav:
  
    follow: Follow
    
    com: &com
      label: Back to Clever Cloud
      url: http://www.clever-cloud.com
    support: &support
      label: Support
      id: support
    
    rss: &rss
      label: RSS
      url: /feed.xml
    twitter: &twitter
      label: Twitter
      url: http://twitter.com/clever_cloud
    facebook: &facebook
      label: Facebook
      url: http://facebook.com/clevercloudsas
    authors: &authors
      label: Authors
      id:    authors
    github: &github
      label: Find us on Github
      url: https://github.com/CleverCloud
    home: &home
      label: Corporate website
      url:   http://www.clever-cloud.com
    press: &press
      label: Press blog
      url:   http://blog.clever-cloud.com
    contact: &contact
      label: Contact
      url:   http://www.clever-cloud.com/en/about
    
    main:
      title: Clever Cloud
      all:   [*twitter, *facebook, *rss]
    sitemap:
    - title: Clever Cloud
      list: [*home, *authors, *press, *contact]
    - title: Follow us
      list: [*twitter, *facebook, *rss, *github]
    - title: Categories
      list: categories
  
  widgets:
    
    categories:
      bare: Yes
    tags:
      bare: Yes
    latest:
      en: Latest posts
    all: [categories, tags, latest]
  
  links: &nav_links
    
    title: Links
    authors: &link_authors
      label: Authors
      id:    authors
    github: &link_github
      label: Find us on Github
      url: https://github.com/CleverCloud
    all: [*link_authors, *link_github]
  
  post:
    
    pub:
      en: Published
    date:
      en: "%m/%d/%Y"
    posted:
      en: Posted on
    pic:
      en: Profile picture of
    more:
      en: Read more
  
  pages:
    
    next:
      en: Next page
    prev:
      en: Previous page
  
  categories:
    
    title: Categories
  
  authors:
    
    adam:
      name:     Quentin Adam
      job:
        en:     Clever Cloud C.E.O
      twitter:  waxzce
    
    decherf:
      name:     Kévin Decherf
      job:
        en:     Office & Production Manager
      twitter:  kdecherf
    
    tayrac:
      name:     Arthur Tayrac
      job:
        en:     Interaction Designer
      twitter:  crmfrsh
    
    durillon:
      name:     Julien Durillon
      job:
        en:     Sytem Administrator and Developer
      twitter:  juuduu
    
    keruspe:
      name:     Marc-Antoine Perennou
      job:
        en:     Java and GNU/Linux Hacker
      twitter:  keruspe
    
    nivolle:
      name:     Clément Nivolle
      job:
        en:     Project Manager
      twitter:  cnivolle
    
    belouin:
      name:     Rodolphe Belouin
      job:
        en:     Javascript & Scala Enthousiast
      twitter:  rbelouin
    
    thommy:
      name:     Kevin Thommy
      job:
        en:     '"Integraphic" Designer'
      twitter:  mon_ke
    
    louerat:
      name:     Bastien Louerat
      job:
        en:     Scala, Akka & Netty Software Developer
      twitter:  blouerat
    
    all: [adam, belouin, louerat, decherf, durillon, nivolle, keruspe, tayrac, thommy]
